config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		if params[:category].blank?
			@articles = Article.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@articles = Article.where(category_id: @category_id).order("created_at DESC")
		end
	end
	def new
		@article = current_user.articles.build
	end
	def show
		
	end
	def create
		@article = current_user.articles.build(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end
	
	def edit
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to root_path
	end


	private 

	def find_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :content, :prepared_by, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_controller_helper.rb
module ArticlesControllerHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Please choose a category"}
	= f.input :title
	= f.input :content
	= f.input :prepared_by
	= f.submit

app/views/articles/edit.html.haml
%h1 Edit Article

= render 'form'

= link_to "Go Back", root_path, class: "btn btn-primary btn-sm"

app/views/articles/index.html.haml
- @articles.each do |article|
	%h2= link_to article.title, article
	%p
		Published at
		= article.created_at.strftime('%b %d, %Y')
	%p= truncate(article.content, length: 150)

app/views/articles/new.html.haml
%h1 New Article

= render 'form'

= link_to "Go Back", root_path, class: "btn btn-primary btn-sm"

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.content
%p= @article.prepared_by

.btn-group
	= link_to "Back", root_path, class: "btn btn-default btn-lg"
	- if user_signed_in?
		= link_to "Edit", edit_article_path(@article), class: "btn btn-success btn-lg"
		= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-lg"

app/views/layouts/application.html.haml
!!!
%html
%head
	%title SAP Wiki
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags 
%body
	%nav.navbar.navbar-default.navbar-fixed-top
		.container
			= link_to "SAPWiki", root_path, class: "navbar-brand"
			%ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li= link_to "New Article", new_article_path
				- else
					%li= link_to "Sign Up", new_user_registration_path
				

	%p.notice= notice
	%p.alert= alert

	.container
		.row
			.col-md-8
				= yield
			.col-md-4
				%ul.list-group
					%li= link_to "All Articles", root_path, class:"list-group-item active"
					- Category.all.each do |category|
						%li= link_to category.name, articles_path(category: category.name), class:"list-group-item"